// apps/demos-vue/src/demos/contextual-zoom.vue
<script setup lang="ts">
import { ref } from 'vue';
import { GrafloriaFlow } from '@grafloria/vue';
import type { DiagramInstance } from '@grafloria/vue';
import { markReady } from '../ready';

// Level-of-detail: the tier the renderer draws is a pure function of zoom. Zoom
// in for full detail (labels, port glyphs); zoom out and it sheds detail through
// medium → sketch → low. The governor is OFF so the tier is a pure function of zoom.
const nodes = Array.from({ length: 12 }, (_, i) => ({
  id: `n${i}`, position: { x: (i % 4) * 200, y: Math.floor(i / 4) * 140 },
  size: { width: 150, height: 70 }, label: `Node ${i}`,
}));
const edges = Array.from({ length: 11 }, (_, i) => ({ id: `e${i}`, source: `n${i}`, target: `n${i + 1}`, type: 'direct' }));

const readout = ref('');
const wrap = ref<HTMLElement | null>(null);
let apiRef: any = null;

function labelCount(host: HTMLElement) { return host.querySelectorAll('svg text').length; }

function tierAt(z: number) {
  try {
    const api = apiRef; if (!api) return;
    api.viewport.setZoom(z);
    api.renderNow();
    const tier = api.getQualityState().tier;
    readout.value = `zoom ${z}×  →  tier "${tier}"  (${labelCount(wrap.value!)} text nodes)`;
  } catch { /* ignore */ }
}

function onInit(api: DiagramInstance) {
  try {
    apiRef = api;
    api.fitView(40);
    tierAt(1.5);
  } catch { /* ignore */ }
  markReady();
}
</script>

<template>
  <div ref="wrap" style="display:flex; flex-direction:column; height:100vh">
    <div style="display:flex; gap:8px; padding:10px 24px; border-bottom:1px solid rgba(127,127,127,.25); align-items:center">
      <span>zoom:</span>
      <button v-for="z in [1.5, 0.7, 0.3, 0.15]" :key="z" @click="tierAt(z)"
        style="padding:5px 12px; border-radius:6px; border:1px solid rgba(127,127,127,.4); background:transparent; color:inherit; cursor:pointer; font:inherit">{{ z }}×</button>
      <span style="margin-left:auto; font:12px/1.4 ui-monospace,monospace; opacity:.85">{{ readout }}</span>
    </div>
    <div style="flex:1; position:relative">
      <GrafloriaFlow :default-nodes="nodes" :default-edges="edges" :renderer-config="{ qualityGovernor: false }" @init="onInit" />
    </div>
  </div>
</template>

// apps/demos-angular/src/app/demos/contextual-zoom/contextual-zoom.component.ts
import { AfterViewInit, Component, ElementRef, viewChild } from '@angular/core';
import { DiagramCanvasComponent } from '@grafloria/angular';
import { markReady } from '../demo-ready';

/** Level-of-detail: the detail the renderer draws follows the zoom. Zoom in for
 *  full labels; zoom out and the renderer sheds detail. The readout reports the
 *  zoom and how much label text reaches the DOM — genuinely different renders. */
@Component({
  standalone: true,
  imports: [DiagramCanvasComponent],
  template: `
    <div style="display:flex;gap:8px;padding:10px 24px;border-bottom:1px solid rgba(127,127,127,.25);align-items:center">
      <span>zoom:</span>
      <button (click)="setZoom(1.5)" style="padding:5px 12px;border-radius:6px;border:1px solid rgba(127,127,127,.4);background:transparent;color:inherit;cursor:pointer">1.5× high</button>
      <button (click)="setZoom(0.7)" style="padding:5px 12px;border-radius:6px;border:1px solid rgba(127,127,127,.4);background:transparent;color:inherit;cursor:pointer">0.7× medium</button>
      <button (click)="setZoom(0.3)" style="padding:5px 12px;border-radius:6px;border:1px solid rgba(127,127,127,.4);background:transparent;color:inherit;cursor:pointer">0.3× sketch</button>
      <button (click)="setZoom(0.15)" style="padding:5px 12px;border-radius:6px;border:1px solid rgba(127,127,127,.4);background:transparent;color:inherit;cursor:pointer">0.15× low</button>
      <span #readout style="margin-left:auto;font:12px/1.4 ui-monospace,monospace;opacity:.85"></span>
    </div>
    <div #host style="height:calc(100vh - 52px)">
      <grafloria-diagram-canvas [(nodes)]="nodes" [(edges)]="edges" style="display:block;height:100%" />
    </div>
  `,
})
export class ContextualZoomComponent implements AfterViewInit {
  canvas = viewChild.required(DiagramCanvasComponent);
  readout = viewChild.required<ElementRef<HTMLElement>>('readout');
  host = viewChild.required<ElementRef<HTMLElement>>('host');
  nodes: any[] = Array.from({ length: 12 }, (_, i) => ({
    id: `n${i}`, position: { x: (i % 4) * 200, y: Math.floor(i / 4) * 140 },
    size: { width: 150, height: 70 }, label: `Node ${i}`,
  }));
  edges: any[] = Array.from({ length: 11 }, (_, i) => ({ id: `e${i}`, source: `n${i}`, target: `n${i + 1}`, type: 'direct' }));

  ngAfterViewInit() {
    this.canvas().fitToContent(40);
    this.setZoom(1.5);
    markReady();
  }

  setZoom(z: number) {
    const vp = this.canvas().viewportController();
    vp?.setZoom(z);
    const texts = this.host().nativeElement.querySelectorAll('svg text').length;
    const el = this.readout()?.nativeElement;
    if (el) el.textContent = `zoom ${z}×  →  ${texts} text nodes in the DOM`;
  }
}
