// apps/demos-vue/src/demos/easy-connect-body.vue
<script setup lang="ts">
import { GrafloriaFlow } from '@grafloria/vue';
import type { DiagramInstance } from '@grafloria/vue';
import { markReady } from '../ready';

// Easy Connect in the ENGINE: press anywhere on a node body and release anywhere
// on another — they wire up, no aiming at a 6px port. The page only flips
// enableEasyConnect; the built-in drag path starts from the nearest port.
const nodes = [
  { id: 'a', position: { x: 100, y: 150 }, size: { width: 200, height: 120 }, label: 'A · press anywhere' },
  { id: 'b', position: { x: 560, y: 150 }, size: { width: 200, height: 120 }, label: 'B · release anywhere' },
];
const edges: never[] = [];

function onInit(api: DiagramInstance) {
  try {
    api.getEngine().setInteractionConfig({ enableEasyConnect: true } as never);
  } catch { /* config optional; canvas still paints */ }
  markReady();
}
</script>

<template>
  <div style="height:100vh">
    <GrafloriaFlow :default-nodes="nodes" :default-edges="edges" @init="onInit" />
  </div>
</template>

// apps/demos-angular/src/app/demos/easy-connect-body/easy-connect-body.component.ts
import { AfterViewInit, Component, viewChild } from '@angular/core';
import { DiagramCanvasComponent } from '@grafloria/angular';
import { markReady } from '../demo-ready';

/** Easy Connect in the ENGINE: press anywhere on a node body and release on
 *  another and they wire up — no aiming at a 6px port. The only wiring is
 *  setInteractionConfig({ enableEasyConnect: true }); the built-in drag path
 *  starts the connection from the nearest port. */
@Component({
  standalone: true,
  imports: [DiagramCanvasComponent],
  template: `
    <grafloria-diagram-canvas [(nodes)]="nodes" [(edges)]="edges" style="display:block;height:100vh" />
  `,
})
export class EasyConnectBodyComponent implements AfterViewInit {
  canvas = viewChild.required(DiagramCanvasComponent);
  nodes: any[] = [
    { id: 'a', position: { x: 100, y: 150 }, size: { width: 200, height: 120 }, label: 'A · press anywhere' },
    { id: 'b', position: { x: 560, y: 150 }, size: { width: 200, height: 120 }, label: 'B · release anywhere' },
  ];
  edges: any[] = [];

  ngAfterViewInit() {
    this.canvas().activeEngine()?.setInteractionConfig({ enableEasyConnect: true } as never);
    markReady();
  }
}
