// libs/renderer-angular/renderer-angular/src/lib/components/grafloria-diagram.component.ts
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  OnDestroy,
  inject,
  input,
  output,
} from '@angular/core';
import { render, type RenderSpec, type RenderOptions } from '@grafloria/element';
import type { DiagramInstance } from '@grafloria/renderer';

/**
 * `<grafloria-diagram>` — the generic kit host. Any kit spec renders:
 *
 * ```ts
 * spec = erDiagram({ entities, relationships });        // or umlDiagram({...}),
 * ```
 * ```html
 * <grafloria-diagram [spec]="spec" (ready)="instance = $event" />
 * ```
 *
 * One component for every present and future kit — because every kit speaks
 * the same contract: a spec with nodes/edges/renderCustomNode/finalize that
 * `render()` mounts in one call.
 */
@Component({
  selector: 'grafloria-diagram',
  template: '',
  styles: [':host { display: block; position: relative; }'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class GrafloriaDiagramComponent implements AfterViewInit, OnDestroy {
  /** Any kit spec — `erDiagram(...)`, `umlDiagram(...)`, `dashboard(...)`, or DSL text. */
  readonly spec = input.required<RenderSpec>();
  /** Options passed through to the underlying `createDiagram`. */
  readonly options = input<RenderOptions>({});
  /** The live DiagramInstance after mount. */
  readonly ready = output<DiagramInstance>();

  private readonly hostRef = inject<ElementRef<HTMLElement>>(ElementRef);
  private instance?: DiagramInstance;

  ngAfterViewInit(): void {
    this.instance = render(this.spec(), this.hostRef.nativeElement, this.options());
    this.ready.emit(this.instance);
  }

  getInstance(): DiagramInstance | undefined {
    return this.instance;
  }

  ngOnDestroy(): void {
    this.instance?.dispose();
    this.instance = undefined;
  }
}

// libs/react/src/lib/grafloria-diagram.tsx
'use client';

/**
 * `<GrafloriaDiagram>` — the generic kit host. Any kit spec renders:
 *
 * ```tsx
 * <GrafloriaDiagram spec={erDiagram({ entities, relationships })}
 *                   onReady={(instance) => …} />
 * ```
 *
 * One component for every present and future kit — every kit speaks the same
 * contract: a spec `render()` mounts in one call.
 */
import { useEffect, useRef } from 'react';
import type { CSSProperties } from 'react';
import { render as renderSpec, type RenderSpec, type RenderOptions } from '@grafloria/element';
import type { DiagramInstance } from '@grafloria/renderer';

export interface GrafloriaDiagramProps {
  /** Any kit spec — `erDiagram(...)`, `umlDiagram(...)`, `dashboard(...)`, or DSL text. */
  spec: RenderSpec;
  /** Options passed through to the underlying `createDiagram`. */
  options?: RenderOptions;
  onReady?: (instance: DiagramInstance) => void;
  className?: string;
  style?: CSSProperties;
}

export function GrafloriaDiagram(props: GrafloriaDiagramProps) {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const latest = useRef(props);
  latest.current = props;

  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;
    let instance: DiagramInstance | null = renderSpec(
      latest.current.spec,
      container,
      latest.current.options ?? {}
    ) as DiagramInstance;
    latest.current.onReady?.(instance);
    return () => {
      instance?.dispose();
      instance = null;
    };
    // Mount once per spec identity.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div
      ref={containerRef}
      className={props.className}
      style={{ position: 'relative', ...props.style }}
    />
  );
}
