// apps/demos-vue/src/demos/floating-edges.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { GrafloriaFlow } from '@grafloria/vue';
import { markReady } from '../ready';

// metadata.connectionPoint: 'smart' floats the edge along the node PERIMETER —
// move B around A and the wire re-attaches to whichever side faces it.
// Repositioning is pure data: the buttons just rewrite the nodes.
const POSITIONS: Record<string, { x: number; y: number }> = {
  right: { x: 620, y: 200 }, below: { x: 220, y: 460 }, corner: { x: 620, y: 460 },
};
const positions = Object.keys(POSITIONS);

const build = (pos: string) => [
  { id: 'a', position: { x: 220, y: 200 }, size: { width: 140, height: 90 }, label: 'A' },
  { id: 'b', position: { ...POSITIONS[pos] }, size: { width: 140, height: 90 }, label: 'B' },
];

const where = ref('right');
const nodes = ref(build('right'));
const edges = [{ id: 'e1', source: 'a', target: 'b', type: 'direct', metadata: { connectionPoint: 'smart' } }];

function place(pos: string) {
  where.value = pos;
  nodes.value = build(pos);
}
onMounted(() => markReady());
</script>

<template>
  <div style="position:relative; height:100vh">
    <div style="position:fixed; top:12px; left:50%; transform:translateX(-50%); z-index:5; display:flex; gap:8px">
      <button v-for="p in positions" :key="p" @click="place(p)"
        :style="{ background: where === p ? '#3B52D9' : '#EEF1FE', color: where === p ? '#fff' : '#3B52D9' }"
        style="padding:6px 14px; border-radius:999px; border:1px solid #94A5F0; font-weight:600; cursor:pointer">
        {{ p }}
      </button>
    </div>
    <GrafloriaFlow :nodes="nodes" :default-edges="edges" />
  </div>
</template>

// apps/demos-angular/src/app/demos/floating-edges/floating-edges.component.ts
import { AfterViewInit, Component } from '@angular/core';
import { DiagramCanvasComponent } from '@grafloria/angular';
import { markReady } from '../demo-ready';

const POSITIONS: Record<string, { x: number; y: number }> = {
  right: { x: 620, y: 200 }, below: { x: 220, y: 460 }, corner: { x: 620, y: 460 },
};

/** metadata.connectionPoint: 'smart' floats the edge along the node PERIMETER —
 *  move B around A and the wire re-attaches to whichever side faces it.
 *  Repositioning is pure data: the buttons just rewrite [(nodes)]. */
@Component({
  standalone: true,
  imports: [DiagramCanvasComponent],
  templateUrl: './floating-edges.component.html',
})
export class FloatingEdgesComponent implements AfterViewInit {
  positions = Object.keys(POSITIONS);
  where = 'right';
  nodes = this.build('right');
  edges = [{ id: 'e1', source: 'a', target: 'b', type: 'direct' as const, metadata: { connectionPoint: 'smart' } }];
  place(pos: string) { this.where = pos; this.nodes = this.build(pos); }
  private build(pos: string) {
    return [
      { id: 'a', position: { x: 220, y: 200 }, size: { width: 140, height: 90 }, label: 'A' },
      { id: 'b', position: { ...POSITIONS[pos] }, size: { width: 140, height: 90 }, label: 'B' },
    ];
  }
  ngAfterViewInit() { markReady(); }
}

<div style="position:fixed; top:12px; left:50%; transform:translateX(-50%); z-index:5; display:flex; gap:8px">
  @for (p of positions; track p) {
    <button (click)="place(p)"
      [style.background]="where === p ? '#3B52D9' : '#EEF1FE'"
      [style.color]="where === p ? '#fff' : '#3B52D9'"
      style="padding:6px 14px; border-radius:999px; border:1px solid #94A5F0; font-weight:600; cursor:pointer">
      {{ p }}
    </button>
  }
</div>
<grafloria-diagram-canvas [(nodes)]="nodes" [(edges)]="edges"
  style="display:block; height:100vh" />
