// apps/demos-react/src/routes.ts
export const ROUTES: Record<string, () => Promise<{ default: React.ComponentType }>> = {
  'nodes/custom-nodes': () => import('./demos/custom-nodes'),
  'nodes/html-nodes': () => import('./demos/html-nodes'),
  'nodes/node-resizer': () => import('./demos/node-resizer'),
  'nodes/auto-sizing': () => import('./demos/auto-sizing'),
  'nodes/connection-limit': () => import('./demos/connection-limit'),
  'nodes/delete-middle-node': () => import('./demos/delete-middle-node'),
  'nodes/drag-handle': () => import('./demos/drag-handle'),
  'nodes/easy-connect': () => import('./demos/easy-connect'),
  'nodes/intersections': () => import('./demos/intersections'),
  'nodes/node-position-animation': () => import('./demos/node-position-animation'),
  'nodes/node-resize-gesture': () => import('./demos/node-resize-gesture'),
  'nodes/node-toolbar': () => import('./demos/node-toolbar'),
  'nodes/proximity-connect': () => import('./demos/proximity-connect'),
  'nodes/rotatable-node': () => import('./demos/rotatable-node'),
  'nodes/shapes': () => import('./demos/shapes'),
  'nodes/stress-test': () => import('./demos/stress-test'),
  'nodes/updating-nodes': () => import('./demos/updating-nodes'),
  'edges/animating-edges': () => import('./demos/animating-edges'),
  'edges/custom-edges': () => import('./demos/custom-edges'),
  'edges/edge-labels': () => import('./demos/edge-labels'),
  'edges/edge-markers': () => import('./demos/edge-markers'),
  'edges/editable-edge': () => import('./demos/editable-edge'),
  'edges/edge-routing': () => import('./demos/edge-routing'),
  'edges/edge-toolbar': () => import('./demos/edge-toolbar'),
  'edges/edge-types': () => import('./demos/edge-types'),
  'edges/floating-edges': () => import('./demos/floating-edges'),
  'edges/jump-overs': () => import('./demos/jump-overs'),
  'edges/parallel-links-and-self-loops': () => import('./demos/parallel-links-and-self-loops'),
  'edges/reconnect-edge': () => import('./demos/reconnect-edge'),
  'edges/routing-algorithms': () => import('./demos/routing-algorithms'),
  'ports/connection-validation': () => import('./demos/connection-validation'),
  'ports/magnet-and-highlight': () => import('./demos/magnet-and-highlight'),
  'ports/port-groups-and-layouts': () => import('./demos/port-groups-and-layouts'),
  'ports/port-labels': () => import('./demos/port-labels'),
  'ports/port-shapes': () => import('./demos/port-shapes'),
  'ports/typed-ports': () => import('./demos/typed-ports'),
  'layout/auto-layout': () => import('./demos/auto-layout'),
  'layout/dagre-tree': () => import('./demos/dagre-tree'),
  'layout/dynamic-layouting': () => import('./demos/dynamic-layouting'),
  'layout/expand-collapse': () => import('./demos/expand-collapse'),
  'layout/elk-tree': () => import('./demos/elk-tree'),
  'misc/minimap-and-controls': () => import('./demos/minimap-and-controls'),
  'diagrams/class-uml': () => import('./demos/class-uml'),
  'diagrams/erd-editor': () => import('./demos/erd-editor'),
  'dashboard/dashboard-builder': () => import('./demos/dashboard-builder'),
  'dashboard/fluid-board': () => import('./demos/fluid-board'),
  'dashboard/nested-containers': () => import('./demos/dashboard-containers'),
  'collab/two-tabs-live': () => import('./demos/two-tabs-live'),
  'collab/comments': () => import('./demos/comments'),
  'misc/mermaid-text': () => import('./demos/mermaid-text'),
  'interaction/computing-flows': () => import('./demos/computing-flows'),
  'interaction/connection-events': () => import('./demos/connection-events'),
  'interaction/context-menu': () => import('./demos/context-menu'),
  'interaction/contextual-zoom': () => import('./demos/contextual-zoom'),
  'interaction/copy-paste': () => import('./demos/copy-paste'),
  'interaction/drag-and-drop': () => import('./demos/drag-and-drop'),
  'interaction/drag-undo': () => import('./demos/drag-undo'),
  'interaction/easy-connect-body': () => import('./demos/easy-connect-body'),
  'interaction/execute-flow': () => import('./demos/execute-flow'),
  'interaction/n8n-workflow': () => import('./demos/n8n-workflow'),
  'interaction/helper-lines': () => import('./demos/helper-lines'),
  'interaction/keyboard-a11y': () => import('./demos/keyboard-a11y'),
  'interaction/marquee-select': () => import('./demos/marquee-select'),
  'interaction/parent-move': () => import('./demos/parent-move'),
  'interaction/preventing-cycles': () => import('./demos/preventing-cycles'),
  'interaction/proximity-connect-live': () => import('./demos/proximity-connect-live'),
  'interaction/save-and-restore': () => import('./demos/save-and-restore'),
  'interaction/touch-device': () => import('./demos/touch-device'),
  'interaction/undo-redo': () => import('./demos/undo-redo'),
  'interaction/validation': () => import('./demos/validation'),
  'layout/force-layout': () => import('./demos/force-layout'),
  'layout/layout-portfolio': () => import('./demos/layout-portfolio'),
  'layout/nested-containers': () => import('./demos/nested-containers'),
  'layout/off-thread-layout': () => import('./demos/off-thread-layout'),
  'grouping/collapse-expand': () => import('./demos/collapse-expand'),
  'grouping/group-frames': () => import('./demos/group-frames'),
  'grouping/parent-child': () => import('./demos/parent-child'),
  'grouping/selection-grouping': () => import('./demos/selection-grouping'),
  'grouping/sub-flow': () => import('./demos/sub-flow'),
  'grouping/swimlanes': () => import('./demos/swimlanes'),
  'styling/dark-mode': () => import('./demos/dark-mode'),
  'styling/css-variables': () => import('./demos/css-variables'),
  'styling/named-style-classes': () => import('./demos/named-style-classes'),
  'styling/paint-servers': () => import('./demos/paint-servers'),
  'styling/theme-bound-properties': () => import('./demos/theme-bound-properties'),
  'styling/themes-and-tokens': () => import('./demos/themes-and-tokens'),
  'dashboard/grid-options': () => import('./demos/grid-options'),
  'styling/turbo-flow': () => import('./demos/turbo-flow'),
  'collab/conflict-resolution': () => import('./demos/conflict-resolution'),
  'collab/live-cursors': () => import('./demos/live-cursors'),
  'collab/offline-and-reconnect': () => import('./demos/offline-and-reconnect'),
  'collab/presentation-mode': () => import('./demos/presentation-mode'),
  'whiteboard/eraser': () => import('./demos/eraser'),
  'whiteboard/freehand-draw': () => import('./demos/freehand-draw'),
  'whiteboard/rectangle': () => import('./demos/rectangle'),
  'whiteboard/stroke-edit': () => import('./demos/stroke-edit'),
  'misc/download-image': () => import('./demos/download-image'),
  'misc/editable-round-trip': () => import('./demos/editable-round-trip'),
  'misc/mermaid-viewer': () => import('./demos/mermaid-viewer'),
  'misc/pdf-export': () => import('./demos/pdf-export'),
  'misc/perf-hud': () => import('./demos/perf-hud'),
  'misc/server-side-export': () => import('./demos/server-side-export'),
  'diagrams/er-advanced': () => import('./demos/er-advanced'),
  'diagrams/scrollable-cards': () => import('./demos/scrollable-cards'),
  'diagrams/table-er': () => import('./demos/table-er'),
  'diagrams/uml-relationships': () => import('./demos/uml-relationships'),
  'diagrams/ai-style-diagram': () => import('./demos/ai-style-diagram'),
  'diagrams/architecture-layout': () => import('./demos/architecture-layout'),
  'diagrams/mermaid-architecture-block': () => import('./demos/mermaid-architecture-block'),
  'diagrams/query-builder': () => import('./demos/query-builder'),
  'diagrams/shape-data': () => import('./demos/shape-data'),
  'diagrams/stencil-palette': () => import('./demos/stencil-palette'),
  'diagrams/visio-editor': () => import('./demos/visio-editor'),
  'edges/highlight-connected': () => import('./demos/highlight-connected'),
  'grouping/drop-to-contain': () => import('./demos/drop-to-contain'),
  'interaction/chatbot-flow': () => import('./demos/chatbot-flow'),
  'misc/drawio-import': () => import('./demos/drawio-import'),
  'nodes/edit-label': () => import('./demos/edit-label'),
  'interaction/workflow-builder': () => import('./demos/workflow-builder'),
  'interaction/marketing-automation': () => import('./demos/marketing-automation'),
  'diagrams/data-modeling': () => import('./demos/data-modeling'),
};
import type React from 'react';

// apps/demos-qwik/gallery/routes.ts
import type { Component } from '@builder.io/qwik';

// route → the Qwik demo for that gallery page (same keys as every other framework app).
export const ROUTES: Record<string, () => Promise<{ default: Component }>> = {
  'nodes/custom-nodes': () => import('./demos/custom-nodes'),
  'nodes/html-nodes': () => import('./demos/html-nodes'),
  'nodes/node-resizer': () => import('./demos/node-resizer'),
  'nodes/auto-sizing': () => import('./demos/auto-sizing'),
  'nodes/connection-limit': () => import('./demos/connection-limit'),
  'nodes/delete-middle-node': () => import('./demos/delete-middle-node'),
  'nodes/drag-handle': () => import('./demos/drag-handle'),
  'nodes/easy-connect': () => import('./demos/easy-connect'),
  'nodes/intersections': () => import('./demos/intersections'),
  'nodes/node-position-animation': () => import('./demos/node-position-animation'),
  'nodes/node-resize-gesture': () => import('./demos/node-resize-gesture'),
  'nodes/node-toolbar': () => import('./demos/node-toolbar'),
  'nodes/proximity-connect': () => import('./demos/proximity-connect'),
  'nodes/rotatable-node': () => import('./demos/rotatable-node'),
  'nodes/shapes': () => import('./demos/shapes'),
  'nodes/stress-test': () => import('./demos/stress-test'),
  'nodes/updating-nodes': () => import('./demos/updating-nodes'),
  'edges/animating-edges': () => import('./demos/animating-edges'),
  'edges/custom-edges': () => import('./demos/custom-edges'),
  'edges/edge-labels': () => import('./demos/edge-labels'),
  'edges/edge-markers': () => import('./demos/edge-markers'),
  'edges/editable-edge': () => import('./demos/editable-edge'),
  'edges/edge-routing': () => import('./demos/edge-routing'),
  'edges/edge-toolbar': () => import('./demos/edge-toolbar'),
  'edges/edge-types': () => import('./demos/edge-types'),
  'edges/floating-edges': () => import('./demos/floating-edges'),
  'edges/jump-overs': () => import('./demos/jump-overs'),
  'edges/parallel-links-and-self-loops': () => import('./demos/parallel-links-and-self-loops'),
  'edges/reconnect-edge': () => import('./demos/reconnect-edge'),
  'edges/routing-algorithms': () => import('./demos/routing-algorithms'),
  'ports/connection-validation': () => import('./demos/connection-validation'),
  'ports/magnet-and-highlight': () => import('./demos/magnet-and-highlight'),
  'ports/port-groups-and-layouts': () => import('./demos/port-groups-and-layouts'),
  'ports/port-labels': () => import('./demos/port-labels'),
  'ports/port-shapes': () => import('./demos/port-shapes'),
  'ports/typed-ports': () => import('./demos/typed-ports'),
  'layout/auto-layout': () => import('./demos/auto-layout'),
  'layout/dagre-tree': () => import('./demos/dagre-tree'),
  'layout/dynamic-layouting': () => import('./demos/dynamic-layouting'),
  'layout/expand-collapse': () => import('./demos/expand-collapse'),
  'layout/elk-tree': () => import('./demos/elk-tree'),
  'misc/minimap-and-controls': () => import('./demos/minimap-and-controls'),
  'diagrams/class-uml': () => import('./demos/class-uml'),
  'diagrams/erd-editor': () => import('./demos/erd-editor'),
  'dashboard/dashboard-builder': () => import('./demos/dashboard-builder'),
  'dashboard/fluid-board': () => import('./demos/fluid-board'),
  'dashboard/nested-containers': () => import('./demos/dashboard-containers'),
  'collab/two-tabs-live': () => import('./demos/two-tabs-live'),
  'collab/comments': () => import('./demos/comments'),
  'misc/mermaid-text': () => import('./demos/mermaid-text'),
  'interaction/computing-flows': () => import('./demos/computing-flows'),
  'interaction/connection-events': () => import('./demos/connection-events'),
  'interaction/context-menu': () => import('./demos/context-menu'),
  'interaction/contextual-zoom': () => import('./demos/contextual-zoom'),
  'interaction/copy-paste': () => import('./demos/copy-paste'),
  'interaction/drag-and-drop': () => import('./demos/drag-and-drop'),
  'interaction/drag-undo': () => import('./demos/drag-undo'),
  'interaction/easy-connect-body': () => import('./demos/easy-connect-body'),
  'interaction/execute-flow': () => import('./demos/execute-flow'),
  'interaction/n8n-workflow': () => import('./demos/n8n-workflow'),
  'interaction/helper-lines': () => import('./demos/helper-lines'),
  'interaction/keyboard-a11y': () => import('./demos/keyboard-a11y'),
  'interaction/marquee-select': () => import('./demos/marquee-select'),
  'interaction/parent-move': () => import('./demos/parent-move'),
  'interaction/preventing-cycles': () => import('./demos/preventing-cycles'),
  'interaction/proximity-connect-live': () => import('./demos/proximity-connect-live'),
  'interaction/save-and-restore': () => import('./demos/save-and-restore'),
  'interaction/touch-device': () => import('./demos/touch-device'),
  'interaction/undo-redo': () => import('./demos/undo-redo'),
  'interaction/validation': () => import('./demos/validation'),
  'layout/force-layout': () => import('./demos/force-layout'),
  'layout/layout-portfolio': () => import('./demos/layout-portfolio'),
  'layout/nested-containers': () => import('./demos/nested-containers'),
  'layout/off-thread-layout': () => import('./demos/off-thread-layout'),
  'grouping/collapse-expand': () => import('./demos/collapse-expand'),
  'grouping/group-frames': () => import('./demos/group-frames'),
  'grouping/parent-child': () => import('./demos/parent-child'),
  'grouping/selection-grouping': () => import('./demos/selection-grouping'),
  'grouping/sub-flow': () => import('./demos/sub-flow'),
  'grouping/swimlanes': () => import('./demos/swimlanes'),
  'styling/dark-mode': () => import('./demos/dark-mode'),
  'styling/css-variables': () => import('./demos/css-variables'),
  'styling/named-style-classes': () => import('./demos/named-style-classes'),
  'styling/paint-servers': () => import('./demos/paint-servers'),
  'styling/theme-bound-properties': () => import('./demos/theme-bound-properties'),
  'styling/themes-and-tokens': () => import('./demos/themes-and-tokens'),
  'dashboard/grid-options': () => import('./demos/grid-options'),
  'styling/turbo-flow': () => import('./demos/turbo-flow'),
  'collab/conflict-resolution': () => import('./demos/conflict-resolution'),
  'collab/live-cursors': () => import('./demos/live-cursors'),
  'collab/offline-and-reconnect': () => import('./demos/offline-and-reconnect'),
  'collab/presentation-mode': () => import('./demos/presentation-mode'),
  'whiteboard/eraser': () => import('./demos/eraser'),
  'whiteboard/freehand-draw': () => import('./demos/freehand-draw'),
  'whiteboard/rectangle': () => import('./demos/rectangle'),
  'whiteboard/stroke-edit': () => import('./demos/stroke-edit'),
  'misc/download-image': () => import('./demos/download-image'),
  'misc/editable-round-trip': () => import('./demos/editable-round-trip'),
  'misc/mermaid-viewer': () => import('./demos/mermaid-viewer'),
  'misc/pdf-export': () => import('./demos/pdf-export'),
  'misc/perf-hud': () => import('./demos/perf-hud'),
  'misc/server-side-export': () => import('./demos/server-side-export'),
  'diagrams/er-advanced': () => import('./demos/er-advanced'),
  'diagrams/scrollable-cards': () => import('./demos/scrollable-cards'),
  'diagrams/table-er': () => import('./demos/table-er'),
  'diagrams/uml-relationships': () => import('./demos/uml-relationships'),
  'diagrams/ai-style-diagram': () => import('./demos/ai-style-diagram'),
  'diagrams/architecture-layout': () => import('./demos/architecture-layout'),
  'diagrams/mermaid-architecture-block': () => import('./demos/mermaid-architecture-block'),
  'diagrams/query-builder': () => import('./demos/query-builder'),
  'diagrams/shape-data': () => import('./demos/shape-data'),
  'diagrams/stencil-palette': () => import('./demos/stencil-palette'),
  'diagrams/visio-editor': () => import('./demos/visio-editor'),
  'edges/highlight-connected': () => import('./demos/highlight-connected'),
  'grouping/drop-to-contain': () => import('./demos/drop-to-contain'),
  'interaction/chatbot-flow': () => import('./demos/chatbot-flow'),
  'misc/drawio-import': () => import('./demos/drawio-import'),
  'nodes/edit-label': () => import('./demos/edit-label'),
  'interaction/workflow-builder': () => import('./demos/workflow-builder'),
  'interaction/marketing-automation': () => import('./demos/marketing-automation'),
  'diagrams/data-modeling': () => import('./demos/data-modeling'),
};
