// apps/demos-react/src/demos/nested-containers.tsx
import { GrafloriaFlow } from '@grafloria/react';
import type { DiagramInstance } from '@grafloria/react';
import { GroupModel } from '@grafloria/element';
import { markReady } from '../ready';

const nodes = ['m1a', 'm1b', 'm2a', 'm2b'].map((id) => ({
  id, position: { x: 0, y: 0 }, size: { width: 90, height: 44 }, label: id,
}));
const edges = [
  { id: 'i1', source: 'm1a', target: 'm1b' },
  { id: 'i2', source: 'm2a', target: 'm2b' },
  { id: 'cross', source: 'm1a', target: 'm2a' },
];

/** Compound layout with a cross-boundary edge induced at the LCA: two labelled
 *  containers, each with two members and an internal edge, and one edge that
 *  crosses between them — the cross edge decides which container sits left. */
export default function NestedContainersDemo() {
  const onInit = (instance: DiagramInstance) => {
    const engine = instance.getEngine() as any;
    (async () => {
      const diagram = engine.getDiagram();
      const g1 = new GroupModel({ id: 'G1', name: 'Container 1' });
      const g2 = new GroupModel({ id: 'G2', name: 'Container 2' });
      diagram.addGroup(g1);
      diagram.addGroup(g2);
      g1.padding = 12;
      g2.padding = 12;
      g1.addMember('m1a', diagram);
      g1.addMember('m1b', diagram);
      g2.addMember('m2a', diagram);
      g2.addMember('m2b', diagram);
      await engine.layout('dagre', { direction: 'LR', nodeSpacing: 30, rankSpacing: 60 });
      markReady();
    })();
  };
  return (
    <div style={{ height: '100vh' }}>
      <GrafloriaFlow defaultNodes={nodes} defaultEdges={edges} onInit={onInit} />
    </div>
  );
}

// apps/demos-vue/src/demos/nested-containers.vue
<script setup lang="ts">
import { GrafloriaFlow } from '@grafloria/vue';
import type { DiagramInstance } from '@grafloria/vue';
import { GroupModel } from '@grafloria/element';
import { markReady } from '../ready';

// Compound layout with a cross-boundary edge induced at the LCA: two labelled
// containers, each with two members and an internal edge, and one edge that
// crosses between them — the cross edge decides which container sits left.
const nodes = ['m1a', 'm1b', 'm2a', 'm2b'].map((id) => ({
  id, position: { x: 0, y: 0 }, size: { width: 90, height: 44 }, label: id,
}));
const edges = [
  { id: 'i1', source: 'm1a', target: 'm1b' },
  { id: 'i2', source: 'm2a', target: 'm2b' },
  { id: 'cross', source: 'm1a', target: 'm2a' },
];

async function onInit(api: DiagramInstance) {
  const engine: any = api.getEngine();
  try {
    const diagram = engine.getDiagram();
    const g1 = new GroupModel({ id: 'G1', name: 'Container 1' });
    const g2 = new GroupModel({ id: 'G2', name: 'Container 2' });
    diagram.addGroup(g1);
    diagram.addGroup(g2);
    g1.padding = 12;
    g2.padding = 12;
    g1.addMember('m1a', diagram);
    g1.addMember('m1b', diagram);
    g2.addMember('m2a', diagram);
    g2.addMember('m2b', diagram);
    await engine.layout('dagre', { direction: 'LR', nodeSpacing: 30, rankSpacing: 60 });
  } catch { /* canvas still paints */ }
  markReady();
}
</script>

<template>
  <div style="height:100vh">
    <GrafloriaFlow :default-nodes="nodes" :default-edges="edges" @init="onInit" />
  </div>
</template>
